//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADFSBankIDSecondFactor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADFSBankIDSecondFactor.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID.
        /// </summary>
        internal static string AdminFriendlyName {
            get {
                return ResourceManager.GetString("AdminFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningsbegäran mot BankID har upphört att gälla..
        /// </summary>
        internal static string BankIDError_Expired {
            get {
                return ResourceManager.GetString("BankIDError_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte gå vidare med Bankidinloggning, kan inte hitta något personnummer..
        /// </summary>
        internal static string BankIDError_NoCivicNumber {
            get {
                return ResourceManager.GetString("BankIDError_NoCivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen matchning på personnummer i BankID..
        /// </summary>
        internal static string BankIDError_NoMatch {
            get {
                return ResourceManager.GetString("BankIDError_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnummer.
        /// </summary>
        internal static string CivicNumber {
            get {
                return ResourceManager.GetString("CivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID som andra faktor.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidContext.
        /// </summary>
        internal static string ErrorInvalidContext {
            get {
                return ResourceManager.GetString("ErrorInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidSessionId.
        /// </summary>
        internal static string ErrorInvalidSessionId {
            get {
                return ResourceManager.GetString("ErrorInvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget personnummer kunde hittas!.
        /// </summary>
        internal static string ErrorMissingCivicNo {
            get {
                return ResourceManager.GetString("ErrorMissingCivicNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoAnswerProvided.
        /// </summary>
        internal static string ErrorNoAnswerProvided {
            get {
                return ResourceManager.GetString("ErrorNoAnswerProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoUserIdentity.
        /// </summary>
        internal static string ErrorNoUserIdentity {
            get {
                return ResourceManager.GetString("ErrorNoUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID.
        /// </summary>
        internal static string FriendlyName {
            get {
                return ResourceManager.GetString("FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öppna appen BankID i din mobiltelefon och följ instruktionerna för att logga in.
        /// </summary>
        internal static string PageBankIdInstruction {
            get {
                return ResourceManager.GetString("PageBankIdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutför inloggningen genom att verifiera din personliga identitet med BankID. Ditt personnummer visas nedan..
        /// </summary>
        internal static string PageBankIdIntroductionText {
            get {
                return ResourceManager.GetString("PageBankIdIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in personnummer.
        /// </summary>
        internal static string PageBankIdIntroductionTitle {
            get {
                return ResourceManager.GetString("PageBankIdIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID MFA.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        internal static string SubmitButtonLabel {
            get {
                return ResourceManager.GetString("SubmitButtonLabel", resourceCulture);
            }
        }
    }
}
